const firebaseAuthErrorCodes = {
  'auth/email-already-in-use': 'El correo electrónico ya está en uso.',
  'auth/invalid-email': 'El correo electrónico no es válido.',
  'auth/operation-not-allowed': 'La operación no está permitida.',
  'auth/weak-password': 'La contraseña es débil.',
  'auth/wrong-password': 'La contraseña es incorrecta.',
  'auth/user-not-found': 'El usuario no existe.',
  'auth/user-disabled': 'El usuario está deshabilitado.',
  'auth/user-token-expired': 'El token de usuario ha expirado.',
  'auth/invalid-credential': 'La credencial no es válida.',
  'auth/invalid-verification-code': 'El código de verificación no es válido.',
  'auth/invalid-verification-id': 'El ID de verificación no es válido.',
  'auth/missing-verification-code': 'Falta el código de verificación.',
  'auth/missing-verification-id': 'Falta el ID de verificación.',
  'auth/invalid-phone-number': 'El número de teléfono no es válido.',
  'auth/invalid-recipient-phone-number': 'El número de teléfono del destinatario no es válido.',
  'auth/invalid-sender-phone-number': 'El número de teléfono del remitente no es válido.',
  'auth/invalid-message-payload': 'El payload del mensaje no es válido.',
  'auth/invalid-message-expiration-time': 'El tiempo de expiración del mensaje no es válido.',
  'auth/invalid-message-priority': 'La prioridad del mensaje no es válida.',
  'auth/missing-message-payload': 'Falta el payload del mensaje.',
  'auth/missing-message-expiration-time': 'Falta el tiempo de expiración del mensaje.',
  'auth/missing-message-priority': 'Falta la prioridad del mensaje.',
  'auth/invalid-multi-factor-info': 'La información de multi-factor no es válida.',
  'auth/invalid-multi-factor-session': 'La sesión de multi-factor no es válida.',
  'auth/missing-multi-factor-info': 'Falta la información de multi-factor.',
  'auth/missing-multi-factor-session': 'Falta la sesión de multi-factor.',
}

export default firebaseAuthErrorCodes